# =========================================
# Day 3 - Similarity Systems

- Cosine similarity
- Euclidean distance
- Document similarity systems

# =========================================

---

# =========================================
# 1. INTUITION
# =========================================

Imgine you and your friend rate movies:

- You both love action, dislike horror - **Similar taste**
- Your friend likes romance, you don't - **Different taste**

Even if your scores different in scale, what matters is:
**How aligned your prefrences are**

That's exactly what similarity systems do for text. 

#### **What problem does this solve?**
- Machines need to measure **how similar two pieces of text are**
- Used in:
    - Search (find relevant documents)
    - Recommendations
    - Duplicate detection

#### **Why was this needed?**
- Text is converted into vectors (BoW, TF-IDF, embeddings)
- Once in vector form -> we need a way to:
    - Compare them
    - Rank them

Key Idea:
**Similarity = how close or aligned two vectors are**

---

# =========================================
# 2. CORE CONCEPTS
# =========================================

#### **2.1 Cosine Similarity**

**Definition**
Mesaures the **angle between two vectors**, not their magnitude

---

**Intuition**
- Same direction -> highly similar
- Opposite direction -> dissimilar
- Orthogonal -> unrelated

---

**Key Insight**
- Focused on orientation, not size
- Perfect for text (where length varies)

---

**Range**
- 1 -> identical
- 0 -> no similarity
- -1 -> opposite

---

#### **2.2 Euclidean Distance**

**Definition**

Mesaures the **straight line distance** between 2 vectors

---

**Intuition**

- Closer points -> more similar
- Far apart -> less similar

---

**Key Insight**
- Sensitive to magnitude (vector length)
- Not ideal when document length differ

---

#### **2.3 Cosine vs Euclidean**

| **Feature** | **Cosine Similarity** | **Euclidean Distance** |
|-------------|-----------------------|------------------------|
| Focus | Direction | Distance |
| Scale sensitivity | No | Yes |
| Best for text | Yes | Limited |

---

#### **2.4 Document Similarity Systems**

**Definition**

Systems that:
- Convert text -> vectors
- Compare vectors -> similarity score
- Rank results

---

#### **2.5 Step-by-Step Working**

1. Preprocess text
2. Convert to vectors (TF-IDF, embeddings)
3. Compute similarity (cosine/distance)
4. Rank results
5. Return most similar documents

---

#### **2.6 Example**

- Doc1: "I love NLP"
- Doc2: "I enjoy NLP"
- Doc2: "I hate cooking"

Expected:
- Doc1 -> Doc2 -> high similarity
- Doc1 -> Doc3 -> low similarity

---

# =========================================
# 3. INTERVIEW NOTES
# =========================================

#### **Key Points**

- Similarity is computed on vector representations
- Cosine similarity is most common used in NLP
- Euclidean distance is less suitable for high-dimensional sparse data

---

#### **Advantages**

**Cosine**
- Scale invariant
- Works well for sparse vector
- Ideal for TF-IDF

**Euclidean**
- Simple 
- Useful in low-dimensional dense spaces

---

#### **Disadvantages**

**Cosine**
- Ignores magnitude differences

**Euclidean**
- Sensitive to scaling
- Poor for high-dimensional sparse data

---

#### **When NOT to Use**

- Euclidean for sparse TF-IDF
- Cosine when magnitude matters

---

#### **Important Comparisons**

**TF-IDF + Cosine vs Embeddings + Cosine**

| **Feature** | **TF-IDF** | **Embeddings** |
| Semantics | No | Yes |
| Use case | Keyword match | Semantic search |

---

# =========================================
# 4. IMPLEMENTATION
# =========================================

#### **4.1 Setup**

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

---

#### **4.2 Sample Data**

In [63]:
docs = [
    "I love NLP",
    "I enjoy NLP",
    "I hate cooking"
]

---

#### **4.3 TF-IDF Vectorizer**

In [64]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)

---

#### **4.4 Cosine Similarity**

In [65]:
cos_sim = cosine_similarity(X)
print("Cosine Similarity:\n", cos_sim) # higher more similar

Cosine Similarity:
 [[1.         0.36644682 0.        ]
 [0.36644682 1.         0.        ]
 [0.         0.         1.        ]]


---

#### **4.5 Euclidean Distance**

In [66]:
euc_dist = euclidean_distances(X)
print("Euclidean Distance:\n",euc_dist) # less distance more similar

Euclidean Distance:
 [[0.         1.12565819 1.41421356]
 [1.12565819 0.         1.41421356]
 [1.41421356 1.41421356 0.        ]]


---

#### **4.6 Document Ranking**

In [67]:
def rank_docs(query, docs):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform([query]+docs)

    sim = cosine_similarity(X[0:1], X[1:]).flatten()
    ranked = sorted(zip(docs, sim), key = lambda x: x[1], reverse = True)

    return ranked

print(rank_docs("I love NLP",docs))

[('I love NLP', np.float64(1.0)), ('I enjoy NLP', np.float64(0.338542631049127)), ('I hate cooking', np.float64(0.0))]


---

#### **4.7 Variation: Using Embeddings**

In [68]:
# from sentence_transformers import SentenceTransformer
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(docs)


cos_sim = cosine_similarity(embeddings)
print(cos_sim)

/home/kartik/Documents/pyworld/NLP_Foundations/nlpenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/kartik/Documents/pyworld/NLP_Foundations/nlpenv/lib/python3.10/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 930.56it/s]
BertModel LOAD REPORT from: sentence-transformers/all-Mini

[[1.         0.9472697  0.2236284 ]
 [0.9472697  1.0000001  0.23665829]
 [0.2236284  0.23665829 0.9999999 ]]


---

# =========================================
# 5. GENAI / LLM / AGENT MAPPING
# =========================================

#### **In LLMs**
- Used in:
    - Embeddings comparison
    - Semantic similarity
    - Retrieval tasks

---

#### **In RAG Systems**
- Core component:
    - Query embedding vs document embedding
    - Similarity -> retrieve top-k documents

---

#### **In AI Agents**
- Used for:
    - Memory retrieval
    - Context matching
    - Tool selection

---

#### **When NOT Needed**
- Direct generation tasks
- Pure prompt-based workflows

---

# =========================================
# 6. MINI PROJECT / TASK
# =========================================


#### **Project: Document Similarity Search Engine**

**Input**

Query: "NLP is amazing"

Documents:
[
    "I love NLP",
    "Cooking is fun",
    "Natural langugage processing is powerful"
]

---

#### **Expected Output**
- Ranked documents based on similarity

---

#### **Steps**
1. Preprocess text
2. Convert to TF-IDF or embeddings
3. Compute cosine similarity
4. Rank documents
5. Return top results

---

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def preprocess_text(docs):

    return [text.lower() for text in docs]

def rank_documents(query,docs):
    docs = preprocess_text(docs)
    query = preprocess_text(query)

    vectorizer = TfidfVectorizer(stop_words='english')
    X = vectorizer.fit_transform(docs)

    que_v = vectorizer.transform(query)

    sim = cosine_similarity(que_v,X).flatten()

    print(sim)
    print(docs)

    ranked = sorted(zip(docs,sim), key = lambda x: x[1], reverse=True)


    return ranked

docs = [
    "I love NLP",
    "Cooking is fun",
    "Natural language processing is powerful"
]

query = ["NLP is amazing"]

print(rank_documents(query,docs))

[0.70710678 0.         0.        ]
['i love nlp', 'cooking is fun', 'natural language processing is powerful']
[('i love nlp', np.float64(0.7071067811865476)), ('cooking is fun', np.float64(0.0)), ('natural language processing is powerful', np.float64(0.0))]


---

# =========================================
# 7. LEARNINGS / SUMMARY
# =========================================

#### **Key Takeaways**

- Similarity is computed in vector space
- Cosing similarity is most important for NLP
- Euclidean distance is less suitable for text

---

#### **Important Insight**

- Representation matters more than metric
- TF-IDF + cosine -> keyword matching
- Embeddings + cosine -> semantic understanding

---

#### **Common Mistakes**

- Using Euclidean on sparse data
- Ignoring normalization
- Expecting semantic meaning from TF-IDF
- Not choosing correct representation

---

# =========================================
# 8. SELF-TEST QUESTIONS
# =========================================

1. **Why do cosine similarity preferred over Euclidean distance in NLP?**

Cosine similarity is preferred over euclidean distance in NLP because it measures the orientation (angle) between vectors rather than their magnitude. In text representation such as TF-IDF or embeddings, document length and word frequency can significantly affect vector magnitude, which can distort euclidean distance. Cosine similarity removes this issue by only focusing on the relative distribution of terms, making it robust to difference in document lenght. Additionally, NLP vectors are often high dimensional and sparse, where euclidean distance becomes less meaningful due to the curse of dimenisonality. As a result, cosine similarity provides more reliable similarity comparisons in most NLP applications.

---

2. **How does vector representation affect similarity results?**

Vector representation directly determines the quality and type of similarity results because similarity matrix operate entirely on these vectors. Different representation captures different aspects of text: for example, Bag of Words and TF-IDF focus on word frequency and keyword overlap, while embeddings capture semantic meaning and contextual relationships. If the represenation lacks semantic information, similarity results will reflect surface level matching rather than true meaning. Conversely, richer representations like embeddings allow the system to identify similarity even when different words convey similar meanings. Therefore, the choice of vector represenation is often more important than the similarity metric itself, as it defines that "similarity" actually means in the system. 

---

3. **Why does TF-IDF + cosine fail for semantic similarity?**

TF-IDF combined with cosine similarity fails on semantic similarity because it represents texts as independent weighted words without capturing context, meaning or relationships between them. It relies purely on terms frequency and inverse document frequency, which emphasize keyword overlap rather than understanding. As a result, two sentences with similar meanings but different words (e.g., "car", "automobile") may appear dissimilar, while sentences sharing common words but different intent may appear similar. This limitation makes TF-IDF effective for keyword based retrieval but inadequate for semantic tasks, where embeddings and transformer based models are more appropriate.

---